name = "CEDICT"
uuid = "76a33514-0aea-4d2f-abaf-6a43b94fc20c"
authors = ["Timothy Lin <32549553+tmthyln@users.noreply.github.com>"]
version = "0.2.1"

[deps]
LazyArtifacts = "4af54fe1-eca0-43a8-85a7-787d91b784e3"
Pipe = "b98c9c47-44ae-5843-9183-064241ee97a0"

[compat]
LazyArtifacts = "1.3"
Pipe = "^1.3"
julia = "^1.3"
